<a href="https://colab.research.google.com/github/Thisun1997/Pytorch_basics/blob/main/linearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear regression from scratch

In [ ]:
import numpy as np
import torch

In [ ]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
w = torch.zeros(2, 3, requires_grad=True)
print(w)

tensor([[0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)


In [ ]:
w = torch.zeros(2, 3, requires_grad=True)
b = torch.zeros(2, requires_grad=True)

def model(x):
    return x @ w.t() + b

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

def fit(inputs,target,w,b):
  for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    print(str(i)+"/100 "+str(loss))
  return preds

In [ ]:
print(fit(inputs,targets,w,b))

0/100 tensor(8327.0996, grad_fn=<DivBackward0>)
1/100 tensor(5767.9951, grad_fn=<DivBackward0>)
2/100 tensor(4041.5645, grad_fn=<DivBackward0>)
3/100 tensor(2876.2847, grad_fn=<DivBackward0>)
4/100 tensor(2089.1802, grad_fn=<DivBackward0>)
5/100 tensor(1556.9453, grad_fn=<DivBackward0>)
6/100 tensor(1196.4860, grad_fn=<DivBackward0>)
7/100 tensor(951.8065, grad_fn=<DivBackward0>)
8/100 tensor(785.1715, grad_fn=<DivBackward0>)
9/100 tensor(671.1518, grad_fn=<DivBackward0>)
10/100 tensor(592.6100, grad_fn=<DivBackward0>)
11/100 tensor(537.9977, grad_fn=<DivBackward0>)
12/100 tensor(499.5325, grad_fn=<DivBackward0>)
13/100 tensor(471.9693, grad_fn=<DivBackward0>)
14/100 tensor(451.7731, grad_fn=<DivBackward0>)
15/100 tensor(436.5622, grad_fn=<DivBackward0>)
16/100 tensor(424.7307, grad_fn=<DivBackward0>)
17/100 tensor(415.1962, grad_fn=<DivBackward0>)
18/100 tensor(407.2293, grad_fn=<DivBackward0>)
19/100 tensor(400.3381, grad_fn=<DivBackward0>)
20/100 tensor(394.1908, grad_fn=<DivBackwar

In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Liner regression from builtins

In [ ]:
import torch.nn as nn
from torch.utils.data import TensorDataset,DataLoader

In [ ]:
#dataset
train_dataset = TensorDataset(inputs, targets)
train_dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
#dataloader
batch_size = 2
train_dataloader = DataLoader(train_dataset, batch_size, shuffle=True)

In [ ]:
batch = 1
for x,y in train_dataloader:
  print("batch",batch)
  print(x)
  print(y)
  batch += 1

batch 1
tensor([[ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[56., 70.],
        [22., 37.]])
batch 2
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 81., 101.],
        [119., 133.]])
batch 3
tensor([[69., 96., 70.]])
tensor([[103., 119.]])


In [ ]:
# Define model
model = nn.Linear(3, 2) # 3 input parameters and 2 outputs

#check the initialised weights and biases
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4143,  0.2412, -0.3284],
        [ 0.4557, -0.2045,  0.3218]], requires_grad=True)
Parameter containing:
tensor([0.2324, 0.4036], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4143,  0.2412, -0.3284],
         [ 0.4557, -0.2045,  0.3218]], requires_grad=True),
 Parameter containing:
 tensor([0.2324, 0.4036], requires_grad=True)]

In [ ]:
import torch.nn.functional as F
loss_fn = F.mse_loss

#Define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) #SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.

# Utility function to train the model
def fit(num_epochs, model, loss_fn, optimizer, train_dataloader):
    # Repeat for given number of epochs
    for epoch in range(num_epochs): 
        # Train with batches of data
        for xb,yb in train_dataloader:   
            # 1. Generate predictions
            pred = model(xb)
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            # 3. Compute gradients
            loss.backward()
            # 4. Update parameters using gradients
            optimizer.step()
            # 5. Reset the gradients to zero
            optimizer.zero_grad()
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
fit(100, model, loss_fn, optimizer, train_dataloader)

Epoch [10/100], Loss: 294.9911
Epoch [20/100], Loss: 2.8295
Epoch [30/100], Loss: 243.4555
Epoch [40/100], Loss: 107.6058
Epoch [50/100], Loss: 26.5874
Epoch [60/100], Loss: 16.7020
Epoch [70/100], Loss: 37.9860
Epoch [80/100], Loss: 2.6499
Epoch [90/100], Loss: 95.7321
Epoch [100/100], Loss: 3.7776


In [ ]:
pred = model(inputs)

In [ ]:
pred

tensor([[ 57.8207,  71.6062],
        [ 78.5177,  99.3712],
        [123.7647, 130.8748],
        [ 26.0438,  46.2902],
        [ 92.8173, 111.7586]], grad_fn=<AddmmBackward>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])